In [1]:
import torch

In [19]:
from torch.autograd import Variable

In [20]:
x = Variable(torch.ones(2,2),requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [21]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [23]:
z = y * y *3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [24]:
z.backward(torch.ones(2,2))
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [25]:
x.grad

tensor([[18., 18.],
        [18., 18.]])

In [26]:
y.grad

In [27]:
z.grad_fn

In [29]:
x.register_hook(lambda grad:grad*2)
y = x + 2
z = y * y *3
z.backward(torch.ones(2,2))
x.grad

tensor([[102., 102.],
        [102., 102.]])

In [33]:
x.grad_fn

In [34]:
y.grad_fn

In [35]:
z.grad_fn

In [58]:


x = torch.tensor([[1,1],[1,1]],dtype=torch.double,requires_grad= True)
y = x + 2
z = y * y * 3
z.backward(torch.tensor([[1,1],[1,1]],dtype=torch.double),retain_graph=True)
print(x.grad)
print(x)

z.backward(torch.tensor([[1,1],[1,1]],dtype=torch.double))
print(x.grad)



tensor([[18., 18.],
        [18., 18.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64, requires_grad=True)
tensor([[36., 36.],
        [36., 36.]], dtype=torch.float64)
