In [2]:
import numpy as np


In [4]:
a = np.arange(24)


In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
a.ndim

1

In [11]:
a.shape

(24,)

In [13]:
a=a.reshape(2,3,4)

In [18]:
a.ndim


3

In [19]:
a.shape

(2, 3, 4)

In [30]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.shape)

(3, 2, 3)


In [5]:
x = np.arange(32).reshape((8,4))

In [6]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
x[[-1,1]]

array([[28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [10]:
x[np.ix_([1,3],[2,3])]

array([[ 6,  7],
       [14, 15]])

In [16]:
a = np.arange(8).reshape([2,2,2])
print(a)

print(np.where(a==6))
print(a[1,1,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(array([1]), array([1]), array([0]))
6


In [19]:
b = np.rollaxis(a,2,0)

print(np.where(b==6))


(array([0]), array([1]), array([1]))


In [36]:
### 广播对象

x = np.array([[1],[2],[3]])
y = np.array([1,2,3])
b = np.broadcast(x,y)

In [37]:
type(b)

numpy.broadcast

In [38]:
r,c = b.iters

In [40]:
type(r),type(c)

(numpy.flatiter, numpy.flatiter)

In [29]:
print (next(r), next(c))
print (next(r), next(c))
b.shape

2 2
2 3


(3, 3)

In [31]:
c = np.empty(b.shape)

In [32]:
c

array([[ 1.14285714, -2.28571429,  0.57142857],
       [-2.28571429,  4.97142857, -1.54285714],
       [ 0.57142857, -1.54285714,  0.88571429]])

In [34]:
c.flat=[u + v for (u ,v) in b]
c

array([[ 5.00000000e+00,  6.00000000e+00,  5.62949953e+14],
       [ 5.62949953e+14,  5.62949953e+14, -6.91752903e+18],
       [-6.91752903e+18, -6.91752903e+18,  5.00000000e+00]])

In [41]:
x + y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [45]:
x = np.array([[1,2],[3,4]])
x.shape

(2, 2)

In [47]:
y = np.expand_dims(x,axis=0)
y.shape

(1, 2, 2)

In [48]:
y

array([[[1, 2],
        [3, 4]]])

In [50]:
y = np.expand_dims(x,axis=1)
y.shape

(2, 1, 2)

In [51]:
y

array([[[1, 2]],

       [[3, 4]]])

In [4]:
data = np.random.randint(0,5,[4,3,2,3])
print(data)

[[[[4 2 4]
   [4 4 3]]

  [[3 2 1]
   [3 1 2]]

  [[2 3 0]
   [3 1 1]]]


 [[[3 2 4]
   [1 3 2]]

  [[4 0 3]
   [0 1 3]]

  [[4 4 4]
   [2 0 1]]]


 [[[4 2 1]
   [2 3 1]]

  [[0 2 0]
   [1 0 3]]

  [[4 3 0]
   [2 3 4]]]


 [[[1 3 4]
   [0 0 2]]

  [[1 1 3]
   [0 2 3]]

  [[3 3 3]
   [2 1 2]]]]


In [5]:
data.sum()

153

In [7]:
tt = data.sum(axis=0)
print(tt)
print(tt.shape)

[[[12  9 13]
  [ 7 10  8]]

 [[ 8  5  7]
  [ 4  4 11]]

 [[13 13  7]
  [ 9  5  8]]]
(3, 2, 3)


In [ ]:
tt = data.sum(axis=0)
print(tt)
print(tt.shape)

In [8]:
tt = data.sum(axis=1)
print(tt)
print(tt.shape)

[[[ 9  7  5]
  [10  6  6]]

 [[11  6 11]
  [ 3  4  6]]

 [[ 8  7  1]
  [ 5  6  8]]

 [[ 5  7 10]
  [ 2  3  7]]]
(4, 2, 3)
