In [1]:
## floor 向下取整数
## ceil 向上取整数
## roud()四舍五入>=0.5
## trunc 裁剪 ，只取整数部分
## frac 只取小数部分
## % 取余


In [2]:
import torch
a = torch.rand(2,2)
a.mul_(10)
a


tensor([[0.4390, 3.9931],
        [3.5584, 6.9069]])

In [3]:
torch.floor(a)

tensor([[0., 3.],
        [3., 6.]])

In [4]:
torch.ceil(a)

tensor([[1., 4.],
        [4., 7.]])

In [5]:
torch.round(a)

tensor([[0., 4.],
        [4., 7.]])

In [6]:
a.trunc()

tensor([[0., 3.],
        [3., 6.]])

In [7]:
a.frac()

tensor([[0.4390, 0.9931],
        [0.5584, 0.9069]])

In [8]:
a%2

tensor([[0.4390, 1.9931],
        [1.5584, 0.9069]])