In [1]:
import torch as t

In [3]:
a = t.tensor([2,3])

In [4]:
b= t.tensor([5,4])

In [5]:
a+b

tensor([7, 7])

In [6]:
a.add(b)

tensor([7, 7])

In [7]:
a.add_(b)


tensor([7, 7])

In [9]:
a

tensor([7, 7])

In [10]:
a = t.tensor([2,3])


In [11]:
a

tensor([2, 3])

In [12]:
a*b


tensor([10, 12])

In [14]:
t.mul(a,b)

tensor([10, 12])

In [15]:
a.mul(b)

tensor([10, 12])

In [19]:
### 二维算术运算--矩阵运算
a = t.ones(2,1)
b = t.ones(1,2)
print(a)
print(b)

print('------')
print (a @ b)


tensor([[1.],
        [1.]])
tensor([[1., 1.]])
------
tensor([[1., 1.],
        [1., 1.]])


In [29]:
a = t.tensor([[1,2]])
b = t.tensor([[3],[4]])
a.mm(b)


tensor([[11]])

In [30]:
a.matmul(b)

tensor([[11]])

In [ ]:
### 对于高维的Tensor（dim>2),定义其矩阵乘法仅在最后的两个维度上，
### 要求当前的维度必须保持一致
## 就象矩阵的索引一样并且运算只有torch.matmul().


In [36]:
a = t.ones(1,2,3,4)
b = t.ones(1,2,4,4)

In [37]:
r = a.matmul(b)
r

tensor([[[[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]],

         [[4., 4., 4., 4.],
          [4., 4., 4., 4.],
          [4., 4., 4., 4.]]]])

In [38]:
r.shape

torch.Size([1, 2, 3, 4])

In [39]:
a = t.tensor([3,4])

In [43]:
###幂运算 
print(t.pow(a,2))
print(a.pow(2))
print(a**2)
a.pow_(2)
print(a)

tensor([ 9, 16])
tensor([ 9, 16])
tensor([ 9, 16])
tensor([ 9, 16])


In [48]:
### exp
a = t.tensor(data=[3,4],dtype=t.float64)
a.exp()

tensor([20.0855, 54.5982], dtype=torch.float64)

In [50]:
a.pow_(2)
a.sqrt()

tensor([ 9., 16.], dtype=torch.float64)

In [53]:
## 对数运算
a = t.tensor([10,101],dtype=t.float64)
t.log10(a)
t.log2(a)

tensor([3.3219, 6.6582], dtype=torch.float64)

In [2]:
import numpy as np


In [10]:
a = np.arange(10*3*3).reshape(10,3,3);
print(a)
print("=====")
a.reshape(30,-1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]]

 [[54 55 56]
  [57 58 59]
  [60 61 62]]

 [[63 64 65]
  [66 67 68]
  [69 70 71]]

 [[72 73 74]
  [75 76 77]
  [78 79 80]]

 [[81 82 83]
  [84 85 86]
  [87 88 89]]]
=====


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [8]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59],
        [60, 61, 62]],

       [[63, 64, 65],
        [66, 67, 68],
        [69, 70, 71]],

       [[72, 73, 74],
        [75, 76, 77],
        [78, 79, 80]],

       [[81, 82, 83],
        [84, 85, 86],
        [87, 88, 89]]])

In [19]:
x = np.arange(10*3*3).reshape(10,3,3);
N , T ,D = x.shape
print(N,T,D)
rx = x.reshape(N*T,-1)
print(rx.shape)
W = np.random.rand(3,10)
print(W)


10 3 3
(30, 3)
[[0.44814102 0.18808043 0.34952047 0.69120414 0.97033077 0.89987372
  0.10871807 0.16469395 0.28571752 0.13933572]
 [0.72393701 0.73606511 0.6291345  0.27778112 0.83530068 0.9205847
  0.97624647 0.00923678 0.90518013 0.6320501 ]
 [0.9839794  0.59357568 0.23724059 0.69480327 0.56709723 0.9663118
  0.1734913  0.18011627 0.09096844 0.08743832]]


In [20]:
corpus=np.array([1,2,3,4,5])
corpus[:-1]

array([1, 2, 3, 4])

In [7]:
import numpy as np
T , H = 5,4

hs = np.random.randn(T,H)
a = np.array([0.8,0.1,0.03,0.05,0.02])
a = a.reshape(5,1)
print(a);
ar = a.repeat(4,axis=1)

print(ar)


t = hs*ar
print(t.shape)
c = np.sum(t,axis = 0)
print(c.shape)


[[0.8 ]
 [0.1 ]
 [0.03]
 [0.05]
 [0.02]]
[[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]
(5, 4)
(4,)


In [24]:
import numpy as np
N, T , H = 10,5,4

hs = np.random.randn(N,T,H)
a = np.random.randn(N,T)


print(a.shape)

ar = a.reshape(N,T,1).repeat(H, axis=-1)
print(ar.shape)




(10, 5)
(10, 5, 4)


In [12]:
print(ar.repeat(H,axis = 2))

[[[ 0.13897777  0.13897777  0.13897777  0.13897777]
  [ 0.74181713  0.74181713  0.74181713  0.74181713]
  [ 0.72977686  0.72977686  0.72977686  0.72977686]
  [-0.45113157 -0.45113157 -0.45113157 -0.45113157]
  [-0.4673244  -0.4673244  -0.4673244  -0.4673244 ]]

 [[ 0.08286739  0.08286739  0.08286739  0.08286739]
  [ 0.38338323  0.38338323  0.38338323  0.38338323]
  [-0.54307417 -0.54307417 -0.54307417 -0.54307417]
  [ 1.60296855  1.60296855  1.60296855  1.60296855]
  [ 0.43308434  0.43308434  0.43308434  0.43308434]]

 [[-0.38209227 -0.38209227 -0.38209227 -0.38209227]
  [ 0.34975622  0.34975622  0.34975622  0.34975622]
  [-0.6480855  -0.6480855  -0.6480855  -0.6480855 ]
  [-0.26303121 -0.26303121 -0.26303121 -0.26303121]
  [ 1.30582648  1.30582648  1.30582648  1.30582648]]

 [[-0.59264854 -0.59264854 -0.59264854 -0.59264854]
  [-1.08133746 -1.08133746 -1.08133746 -1.08133746]
  [ 0.19920146  0.19920146  0.19920146  0.19920146]
  [-0.30757423 -0.30757423 -0.30757423 -0.30757423]
  [-1.

In [17]:
ar = ar.repeat(H,axis = -1)
print(hs.shape)
print(ar.shape)

(10, 5, 4)
(10, 5, 256)
