In [1]:
import torch


In [3]:
a = torch.rand(2,5)
b = torch.ones(2,5)
print(a)
print(b)


tensor([[0.4252, 0.7182, 0.3749, 0.3281, 0.2121],
        [0.2653, 0.6621, 0.9964, 0.6543, 0.6010]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [4]:
a>0.5

tensor([[False,  True, False, False, False],
        [False,  True,  True,  True,  True]])

In [5]:
torch.where(a>0.5,a,b)

tensor([[1.0000, 0.7182, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.6621, 0.9964, 0.6543, 0.6010]])

In [7]:
a = torch.rand(4,5)
print(a)

tensor([[0.4627, 0.6423, 0.2536, 0.9087, 0.1985],
        [0.2673, 0.0692, 0.4518, 0.4882, 0.6034],
        [0.4774, 0.4317, 0.7201, 0.6054, 0.2720],
        [0.9829, 0.4600, 0.3985, 0.2838, 0.3990]])


In [9]:
torch.index_select(a,dim=0,index=torch.tensor([0,2]))

tensor([[0.4627, 0.6423, 0.2536, 0.9087, 0.1985],
        [0.4774, 0.4317, 0.7201, 0.6054, 0.2720]])

In [18]:
a = torch.linspace(start=1,end=16,steps=16).view(4,4)

In [19]:
a

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [31]:
a.gather(dim=0,index=torch.tensor([[0,1,1,1],
                                  [0,1,3,1],
                                  [0,1,1,1],
                                  [0,1,1,1]]))

tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 15.,  8.],
        [ 1.,  6.,  7.,  8.],
        [ 1.,  6.,  7.,  8.]])

In [39]:
mask = torch.zeros_like(a,dtype=torch.bool)
mask[0][1]=1
mask

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [40]:
a.masked_select(mask=mask)

tensor([2.])

In [42]:
a.take(torch.tensor([0,15]))

tensor([ 1., 16.])

In [43]:
a = torch.tensor([[1,0,12,0,15],
                 [1,0,0,13,10]])


In [44]:
a.nonzero()

tensor([[0, 0],
        [0, 2],
        [0, 4],
        [1, 0],
        [1, 3],
        [1, 4]])