In [1]:
import torch


In [2]:
a = torch.linspace(1,6,6).view(2,3)

In [3]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
torch.reshape?

In [5]:
torch.reshape(a,(3,2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [7]:
torch.arange?

In [9]:
torch.t(a)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [11]:
torch.transpose(a,0,1)


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [12]:
import cv2

ModuleNotFoundError: No module named 'cv2'