In [1]:
import numpy as np


In [9]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

## 神经网络推理全貌

In [10]:
x=np.random.randn(10,2)
print("x=")
print(x)
W1 = np.random.randn(2,4)
print("W1=")
print(W1)

b1 = np.random.randn(4)

W2=np.random.randn(4,3)
print("w2=")
print(W2)
b2=np.random.randn(3)


h = np.dot(x,W1) + b1
print("h=")
print(h)
print(h.shape)

a = sigmoid(h)



s = np.dot(a,W2) + b2
print("s=")
print(s)



x=
[[-0.3398497   0.21497859]
 [ 0.00937429  1.05489241]
 [-0.16548167  0.84235224]
 [ 0.35109942 -0.61964048]
 [-1.44630703 -0.73637301]
 [ 2.24255756 -2.04257363]
 [ 0.56265777 -0.40848048]
 [-0.61041007 -0.31083496]
 [-0.08579526 -0.56299889]
 [-0.17304437  0.4292496 ]]
W1=
[[-1.21115295  0.53908396  2.59375129  0.76797469]
 [-0.3359235  -0.29398607  0.59764172  1.23090308]]
w2=
[[ 0.4609115   1.06701104 -0.27842163]
 [ 0.05348836  1.82748579  1.67448873]
 [-0.33235602  1.14723834  0.23426216]
 [ 0.77460575  0.84422288 -0.02863544]]
h=
[[ 2.33088280e-01 -3.70485738e-01 -3.40569084e+00  3.42488280e-01]
 [-4.72022172e-01 -4.29147649e-01 -1.99792313e+00  1.64453597e+00]
 [-1.88847630e-01 -4.60925843e-01 -2.57847886e+00  1.24863468e+00]
 [-3.23388618e-01  2.47360228e-01 -2.11234385e+00 -1.54215469e-01]
 [ 1.89275870e+00 -6.87275020e-01 -6.84413338e+00 -1.67826457e+00]
 [-2.13623703e+00  1.68533749e+00  1.94322392e+00 -4.53116292e-01]
 [-6.50551741e-01  2.99329843e-01 -1.43741609e+00  2.

## 神经网络正向传播


In [74]:
y = np.array([
    [0.1,0.2,0.7],
    [0.2,0.2,0.6],
    [0.5,0.2,0.3]
])

t = np.array([
    [0,0,1],
    [1,0,1],
    [1,0,1]
])

#print(t)
#print(y)

c = np.c_[1-y,y]


t*np.log(c) 


ValueError: operands could not be broadcast together with shapes (3,3) (3,6) 

In [57]:
tmp = np.array([1,2,3])
print(tmp)
# print(tmp.ndim)
# print(tmp.size)

print(tmp.shape)
tmp=tmp.reshape(1,tmp.size)
print(tmp)
# sig = Sigmoid()
# sig.forward(tmp)
print("...")
tmp = np.log(tmp)
np.sum(tmp)


[1 2 3]
(3,)
[[1 2 3]]
...


1.791759469228055

array([0.11853167, 0.32220249, 0.11853167, 0.32220249, 0.11853167])

In [42]:
tmp = np.array([.1,.2,.3,.0,.2,.1])

In [43]:
tmp.argmax()   ## 取出数组中最大值的索引


2

In [44]:
np.random.choice?

In [61]:
tmp = np.arange(10)
tmp >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [64]:
np.maximum?


In [90]:
test = np.arange(27)

test = np.reshape(test,(3,3,3))
print(test)
print("=====")
print(test[:,1,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
=====
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


In [86]:
np.reshape?