In [1]:
import numpy as np
## numpy广播机制

In [7]:
A = np.array([
    [.5 , .2 , .3],
    [.3 , .5 , .2],
    [.2 , .3 , .5],
])
print("A:\n",A)

B = b = np.array([
    .5 , .5,
    .4 , .6,
    .7 , .3
]).reshape((3,2))
print("B:\n",B)

pi = np.array([
    .2,
    .4,
    .4
]).reshape((3,1))

print("pi:\n",pi)



A:
 [[0.5 0.2 0.3]
 [0.3 0.5 0.2]
 [0.2 0.3 0.5]]
B:
 [[0.5 0.5]
 [0.4 0.6]
 [0.7 0.3]]
pi:
 [[0.2]
 [0.4]
 [0.4]]


In [23]:
T1_prev = b[:,0].reshape((3,1))*pi
print("T1_prev:")
print(T1_prev)

p_Obs_State = B[:, 1]
p_Obs_State = np.expand_dims(p_Obs_State,axis=0)

print("p_Obs_State")
print(p_Obs_State)



T1_prev:
[[0.1 ]
 [0.16]
 [0.28]]
p_Obs_State
[[0.5 0.6 0.3]]


In [31]:
dd = T1_prev*A*p_Obs_State
dd

array([[0.025 , 0.012 , 0.009 ],
       [0.024 , 0.048 , 0.0096],
       [0.028 , 0.0504, 0.042 ]])

In [33]:
np.max(dd,axis = 0)

array([0.028 , 0.0504, 0.042 ])

In [34]:
np.argmax(dd,axis=0)

array([2, 2, 2])