In [3]:
import numpy as np
import sys
sys.path.append("/Users/wzp/book/nature_language")


In [14]:
c0 = np.array([[1, 0, 0, 0, 0, 0, 0],[1, 0, 0, 0, 0, 0, 0],[1, 0, 0, 0, 0, 0, 0]])
c1 = np.array([[0, 0, 1, 0, 0, 0, 0],[1, 0, 0, 0, 0, 0, 0],[1, 0, 0, 0, 0, 0, 0]])

In [15]:
# 权重的初始值
W_in = np.random.randn(7, 3)
W_out = np.random.randn(3, 7)

In [16]:
# 生成层
in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

In [17]:
h0 = in_layer0.forward(c0)
h1 = in_layer1.forward(c1)

In [18]:
print(h0)

print(h1)

[[ 0.07788752 -0.15767681  1.16739658]
 [ 0.07788752 -0.15767681  1.16739658]
 [ 0.07788752 -0.15767681  1.16739658]]
[[ 1.16212667 -0.93215063 -0.01857847]
 [ 0.07788752 -0.15767681  1.16739658]
 [ 0.07788752 -0.15767681  1.16739658]]


In [23]:
h = 0.5*(h0 + h1)


s = out_layer.forward(h)


from common.layers import Sigmoid
sigmoid = Sigmoid()

print(s)


print(sigmoid.forward(s))


[[ 0.88084632 -0.22449704  0.5721331   1.04931332  0.93735029  1.95658911
  -1.99048525]
 [ 0.91936715 -1.27991459 -0.07103989  1.11154996  0.11858709  1.94349441
  -1.0647325 ]
 [ 0.91936715 -1.27991459 -0.07103989  1.11154996  0.11858709  1.94349441
  -1.0647325 ]]
[[0.70699757 0.44411027 0.63925523 0.74064302 0.71856412 0.87616334
  0.12020554]
 [0.71491314 0.21756476 0.48224749 0.75241796 0.52961208 0.87473554
  0.25640611]
 [0.71491314 0.21756476 0.48224749 0.75241796 0.52961208 0.87473554
  0.25640611]]
