In [17]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))


In [3]:
x = np.random.randn(10,2);
x


array([[ 0.9991962 , -0.43497943],
       [ 2.34412502,  0.5718663 ],
       [ 1.62921845, -0.67996628],
       [-1.25100068, -1.05997093],
       [ 0.02235364, -0.81991934],
       [-0.0928931 ,  1.71081892],
       [ 1.29300937,  0.38668147],
       [ 1.05883389, -0.31239089],
       [-0.70548938,  0.95403834],
       [ 0.48032573,  0.94690399]])

In [5]:
w1 = np.random.randn(2,4)
w1

array([[-0.04599351,  0.34335686, -1.79231629, -1.13859271],
       [ 0.97594628,  1.28222202, -1.11046212,  0.24654882]])

In [6]:
b1 = np.random.randn(4)
b1

array([ 1.8262097 ,  0.39581353, -0.88855317, -0.36270158])

In [7]:
w2 = np.random.randn(4,3)
w2

array([[ 1.2912808 ,  0.5649271 ,  0.73459122],
       [-0.5255317 ,  1.06578775, -2.95883329],
       [-1.19584838,  0.7688602 , -0.95378774],
       [-0.41736024,  0.46279742,  0.2992786 ]])

In [8]:
b2 = np.random.randn(3)


In [9]:
b2

array([-1.34311342, -2.52222811,  0.75050464])

In [22]:
h=np.dot(x,w1) + b1
h.shape
h

array([[ 1.3557366 ,  0.1811542 , -2.19640061, -1.60762275],
       [ 2.27650595,  1.93394449, -5.7250025 , -2.89071228],
       [ 1.08766566,  0.08334913, -3.05355115, -2.38536272],
       [ 0.84927292, -1.39284419,  2.5306933 ,  0.80034408],
       [ 1.02498435, -0.64782982, -0.0181286 , -0.59030342],
       [ 3.50014955,  2.55756774, -2.62185895,  0.16486622],
       [ 2.14412   ,  1.33558866, -3.63543005, -1.73957677],
       [ 1.47263348,  0.35881694, -2.43942016, -1.64530174],
       [ 2.7897478 ,  1.37686788, -0.68351649,  0.67578051],
       [ 2.72824526,  1.77487781, -2.80094981, -0.67613889]])

In [21]:
a= sigmoid(h)
a

array([[0.79506591, 0.5451651 , 0.10007418, 0.16691892],
       [0.90691249, 0.87368537, 0.00325273, 0.0526146 ],
       [0.7479419 , 0.52082523, 0.04506441, 0.08429569],
       [0.7004146 , 0.19895409, 0.92626572, 0.69004808],
       [0.73594235, 0.34347875, 0.49546797, 0.35656524],
       [0.97069202, 0.92808028, 0.0677448 , 0.54112345],
       [0.89511803, 0.79176356, 0.02569495, 0.1493667 ],
       [0.81345733, 0.58875402, 0.08021568, 0.16174494],
       [0.94211929, 0.7984875 , 0.33547691, 0.6627963 ],
       [0.9386729 , 0.85506323, 0.05727287, 0.33712361]])

NameError: name 'sigmoin' is not defined

In [24]:
import numpy as np
D,N = 8,7


In [25]:
x = np.random.randn(1,D)
x

array([[-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047]])

In [26]:
y = np.repeat(x,N,axis=0)
y

array([[-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047],
       [-2.62339156,  1.0144733 ,  0.60992325, -0.18155086, -0.30538925,
        -0.9419248 ,  1.61238393,  0.64343047]])

In [27]:
y.shape

(7, 8)

In [31]:
test =np.array([
    [1,2,3],
    [4,5,6],
         ])

In [32]:
test

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.sum(test,axis=0,keepdims=False)

array([5, 7, 9])

In [39]:
np.sum(test,axis=1,keepdims=True)

array([[ 6],
       [15]])

In [6]:
import sys
sys.path.append("/Users/wzp/book/【源代码】深度学习进阶：自然语言处理");

In [8]:
from dataset import spiral


In [9]:
import matplotlib.pyplot as plt

In [10]:
x , t = spiral.load_data()

In [7]:
x.shape

(300, 2)

In [8]:
t.shape

(300, 3)

In [13]:
t

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [14]:
x

array([[-0.00000000e+00,  0.00000000e+00],
       [-9.76986432e-04,  9.95216044e-03],
       [ 5.12668241e-03,  1.93317647e-02],
       [-3.86043324e-04,  2.99975161e-02],
       [ 1.42509650e-02,  3.73752591e-02],
       [ 9.41914082e-04,  4.99911272e-02],
       [ 2.25361319e-02,  5.56068589e-02],
       [ 6.52848904e-03,  6.96948982e-02],
       [ 2.50649535e-02,  7.59720219e-02],
       [ 2.03287580e-02,  8.76740646e-02],
       [ 5.98440862e-02,  8.01166983e-02],
       [ 6.19050693e-02,  9.09272368e-02],
       [ 3.22809763e-02,  1.15576549e-01],
       [ 8.28423530e-02,  1.00185551e-01],
       [ 1.09856959e-01,  8.67839183e-02],
       [ 9.33208222e-02,  1.17436043e-01],
       [ 7.82976217e-02,  1.39533087e-01],
       [ 1.23994559e-01,  1.16298535e-01],
       [ 8.06199110e-02,  1.60936105e-01],
       [ 1.39235917e-01,  1.29280158e-01],
       [ 1.53599653e-01,  1.28090384e-01],
       [ 1.38981638e-01,  1.57429680e-01],
       [ 1.89873275e-01,  1.11122183e-01],
       [ 1.

In [18]:
import numpy as np
np.random.permutation(4)

array([2, 0, 3, 1])